### ISSUE TITLE
Error loading index.html

### ISSUE THREAD

**Issue by garyns** [salboaie/SwarmESB#18]
Hi,
I'm trying to evaluate SwarmESB - On a Mac. (Supported?).

When I browse to localhost:8080, I get "Error loading index.html" (I get 8080 from the console output, not 8081 as in the install docs). The console also reports the following error.

`Error: Cannot find module 'swarm-winston'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/smgary/Downloads/SwarmESB/node_modules/swarmcore/etc/adapters/DefaultLogger.js:8:15)
....`

**Comment by asaccool** [comment]
Hi,

SwarmESB is platform independent as long as Node.js can be runned on it.
The issues that you experiment are related to some libraries that are not up-to-date on npm repositories because we are working on a new version.
To solve this issues at this moment please clone into node_modules folder the git version of swarmcore instead of npm one: https://github.com/PrivateSky/swarmcore. Also clone swarm-winston from https://github.com/CiprianTalmacel/swarm-winston. And offcourse after that you need to run npm install into swarmcore and swarm-winston folder to solve their dependecies.
