### ISSUE TITLE
APP require 'swarmcore' module

### ISSUE THREAD

**Issue by Petro-Kashpurenko** [salboaie/SwarmESB#9]
When trying to launch, getting the following message:
Cannot find module 'swarmcore'

```
Error: Cannot find module 'swarmcore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/www/SwarmESB/adapters/demoLaunch.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

The APP does not start.

Installation of swarmcore through does not help either.

**Comment by salboaie** [comment]
Sorry, this repository is not very well tested, I'm working right now to stabilize and make it work. See the first statement in README.md. Go directly to swarmcore and follow install instructions from there,

**Comment by salboaie** [comment]
i'm closing this issue. current version in main branch is fine enough now.
